
var comments = [
  // NICOLE SAMUELSON
  "Cute!",
  "so so cute tho!!!",
  "cutie!!",
  "aw this is so cute!",
  "skinny legend",
  "cute!!",
  "Cutie!!",
  "yes you're such a cutie",
  "Omg cute!!!",
  "Ur beautiful hunny",
  "Super cuteee!!!",
  "UR SO CUTE",
  "YOU'RE SO CUTE",
  "So cuteee!! Miss ya so much!!",
  "cutie!",
  "The Best Nickel In The Piggy Bank!",
  "What a beauty!",
  "cutee",
  "cute!!",
  "cutie",
  "these are so cute!!",
  "your so pretty!!",
  "Super cute!!!",
  "Ooo oo cuteeeee",
  "cutieeeeee",
  "cuuuutie",
  "oooh cute!!",
  "so",
  "dang",
  "cute",
  "You're adorable",
  "So cute!",
  "You're the cutest!!!!",
  "So cute!",
  "These are sooo cute",
  "Wow",
  "This is pretty dang cute",
  "oooh so cute!!",
  "cute!",
  "aww cute!! miss ya",
  "cuties",

  // MARISSA MANNHARDT
  "YOURE BEAUTIFUL",
  "adorableeeee",
  "Wait omg why are you so gorgeous",
  "You're so gorge!!",
  "ahh super cute!",
  "very very cute",
  "ahh cute marissa!",
  "Beautiful pictures",
  "Sooo gorgeous",
  "Perfection",
  "I LOVE YOU UR SO CUTE",
  "You're so cute Marissa!!",
  "you're so pretty wth!!",
  "so pretty",
  "<3 ily",
  "god darn we are so cute",

  // LYDIA MONK
  "big cutie",
  "beautiful",
  "I-",
  "lookin at you",
  "woah",
  "Beauty and classy",
  "Whoaaaa",
  "stunner",
  "gorgeous girl",
  "This is lovely",
  "cutie",
  "so pretty!",
  "cute and colorful",
  "STUNNING",
  "love it!",
  "y'all look stunning",
  "Waouh it's stunning !",
  "wow queen",
  "Cute!!!",
  "Pretty!",

  // NOELLE GLASSBRENNER
  "so cute!!",
  "cute!!!",
  "guys look how cute my best friend is",
  "super cute!!",
  "So cute!!",
  "so cute noelle",
  "super cute noelle!!!",
  "so pretty",
  "cute noelle!!",
  "Okay wow so gorgeous!!!!!",
  "so cute noelle",
  "super cuteee",
  "Super cute!",
  "Pretty!!!",
  "Gorgeous!!!!",
  "So pretty!!",
  "super cute noel!",
  "You’re soo pretty!!! Omgggg I miss you sm!!",
  "You cute",

  // HANNAH CROWELL
  "what a rockstar!!",
  "this is so cute and good job!!",
  "PROUD!!",
  "YASSSS UR SO FREAKING PERFECT I CANT WAIT TO ROOM W UUUUUUU",
  "You are so hot!",
  "ur HOT AS A MOFO",
  "I’m obsessed w/ this",
  "my favorite human being in the entire world",
  "Honeyyyyyy",
  "HANNAH I LOVE YOUU",
  "Dang you’re cute!",
  "Miss this‼️ you’re eaux so cute",
  "Omg stunna",
  "Why are you so stinking cute?",
  "Yes yes YES THATS MY BESTIE!!! WORK IT GIRL",
  "WOW OKAY you are STUNNING",
  "ohmygosh, YES",
  "OK YES ILY",
  "beautiful",
  "cute",
  "love",
  "super cute!!",
  "Lovely lady",
  "Hannah you are glowing!!!!",
  "Cute!!!!!",
  "LOVE THIS",
  "We LOVE LOVE LOVE this",
  "Love everything about this!!",
  "THATS MY BABYYYYYYYYY",
  "OKAY SO CUTE",
  "WOW U R PERFECT!!!!",

  //LIZZY CERVANKA
  "Luv u :)",
  "I love you SO VERY BIG",
  "Cuties",
  "supa cute",
  "why is ur smile literally the cutest thing in the entire universe????? i donut understand",
  "you're beautiful!!",
  "breathtaking, actually",
  "holy",
  "You're gorgeous",
  "Pretty girl",
  "lizzy",
  "Live your best life girl!!",
  "WOW",
  "GORGEOUS.",
  "pretty bby",
  "PRETTYYYT",
  "Damn ok sis I see you",
  "THE cutest ever!!!!!",
  "Pretty",
  "wowzaaaaa",
  "the cutest human ever",
  "soooo cute Lizzy!!",
  "You're gorgeous and I love you:)",
  "Cuties",
  "my bootyful friend",
  "what a cutie!",
  "the cutest girls out there",
  "cute cute cute",
  "awwww",
  "Beauty",
  "Pretty!",
  "wow you're adorable",
  "i'm smiling because you are",
  "qt",
  "Damn girl you look'en cute!!",
  "omg I love you liz",
  "look at my beautiful friend",
  "Aghg you're so pretty",
  "Beautiful hunny",
  "Too cute",
  "you're so cute lizzy",
  "wowie",
  "why are you literally THE cutest",



  // MOLLYS FRIENDS
  "literally perfect",
  "Too cute for my feed",
  "pretty girls :)",
  "cute!!",
  "beautiful babes",
  "Qt",
  "dayum",
  "you're sooo pretty",
  "cute cute cute!!",
  "oooo",
  "I'm jealous",
  "im going to sign you up for modeling if you don't",
  "cute cute cute",
  "you're. too. cute.",
  "Ur so gorgeous it's not fair",
  "supa cute",
  "cutie",
  "stunning, gorgeous, pretty, cute, beautiful!! Your all of themmmmmm",
  "omg so cute",
  "HOLY COW",
];

var fullcomments = [
  // NICOLE SAMUELSON
  "Just like when you reffed my soccer games",
  "closing your eyes to block out the haters",
  "Wouldn't be a pic without ur eyes closed",
  "YEET SKEET",
  "This is so baller of you",
  "so swol wow and cute!",
  "Nicole u cute",
  "nicole",
  "dang alright nicole",
  "Nicole you are so adorable!!",
  "nicole!!!!!",
  "surprised we made it out of the mini maze",
  "still full from the stolen apples",
  "nicole you're so cute",

  // MARISSA MANNHARDT
  "even if u look homeless i still luv u",
  "don't run me over",
  "yay!! Also pretty girl",
  "now i have a driver ;) nice job!",
  "what a baller ;)",

  // LYDIA MONK
  "Stewart",
  "oi oi baguette",
  "an intellectual",
  "Why are you so cliche?",
  "insanely cute Lyd",
  "WOWOWOW LYDIA",
  "I'm a man of simple tastes. I see bread, I like.",

  // NOELLE GLASSBRENNER
  "Love the suit ;)",
  "and got just as many bug bites",
  "good one",
  "I want you to know the only reason I liked this post was because of the caption",

  // HANNAH CROWELL
  "Absolutely the best 13.1 miling Hannah ever!!!!!",
  "SO proud of you b!!!",
  "omg runner who??????",
  "did u run in the chacos",
  "You’re saying you want to come hang out with my kids!!!",

  // LIZZY CERVANKA
  "can't believe you and emily got infront of nicole and I's photo",
  "What's your number!",
  "oh my ghandi",

  // MOLLYS FRIENDS
  "Look at my crocs there literally yellow.",
  "Meow meow",

];